apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      containers:
      - name: flask-app-1
        image: flask-docker-traffic-balancer-flask-app1:latest
        env:
        - name: APP_NAME
          value: "Flask App 1"
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app1
spec:
  selector:
    app: flask-app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000