apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app2
  template:
    metadata:
      labels:
        app: flask-app2
    spec:
      containers:
      - name: flask-app-2
        image: flask-docker-traffic-balancer-flask-app2:latest
        env:
        - name: APP_NAME
          value: "Flask App 2"
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app2
spec:
  selector:
    app: flask-app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
